name: Terraform Apply

on: 
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key'
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: false
      AWS_SESSION_TOKEN:
        description: 'AWS Session Token'
        required: false
      AWS_DEFAULT_REGION:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'
      DEPLOY_ENVIRONMENT:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - dev-01
          - main
      TF_STATE_BUCKET:
        description: 'Terraform State Bucket'
        required: false
        default: 's1sg-tc-terraform-state-bucket-hackaton'
        type: choice
        options:
          - s1sg-tc-terraform-state-bucket-hackaton
          - s1sg-tc-terraform-state-bucket-hackaton-dev
          - s1sg-tc-terraform-state-bucket-hackaton-dev-01
          - s1sg-tc-terraform-state-bucket-hackaton-main
      TF_STATE_KEY:
        description: 'Terraform State Key'
        required: false
        default: 'terraform.tfstate'
      svc_hackaton_image_tag:
        description: 'The tag of the image for the hackaton service without svc'
        required: false
        default: 'develop'
        type: choice
        options:
          - develop
          - ${{ github.base_ref }}
          - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN || secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ github.event.inputs.AWS_DEFAULT_REGION }}

    - name: Terraform Init
      run: terraform init -upgrade -backend-config="bucket=${{ github.event.inputs.TF_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.TF_STATE_KEY }}" -backend-config="region=${{ github.event.inputs.AWS_DEFAULT_REGION }}"
      working-directory: './IaC'

    - name: Set redeploy annotation
      run: echo "TF_VAR_redeploy_annotation=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      working-directory: './IaC'

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: './IaC'
      env:
        TF_VAR_environment: ${{ github.event.inputs.DEPLOY_ENVIRONMENT }}
        TF_VAR_image_registry: "ghcr.io/soat1stackgolang"
        TF_VAR_svc_hackaton_image_tag: "${{ github.event.inputs.svc_hackaton_image_tag }}" # The tag of the image for the hackaton service without svc
